export const helloArray = [
  { hello: 'Hello', language: 'English' },
  { hello: 'Hola', language: 'Spanish' },
  { hello: 'Bonjour', language: 'French' },
  { hello: 'Guten Tag', language: 'German' },
  { hello: 'Ciao', language: 'Italian' },
  { hello: 'Konnichiwa', language: 'Japanese' },
  { hello: 'Namaste', language: 'Hindi' },
  { hello: 'Annyeonghaseyo', language: 'Korean' },
  { hello: 'Salaam', language: 'Arabic' },
  { hello: 'Zdravstvuyte', language: 'Russian' },
  { hello: 'Nǐ hǎo', language: 'Mandarin Chinese' },
  { hello: 'Olá', language: 'Portuguese' },
  { hello: 'Sawatdee', language: 'Thai' },
  { hello: 'Merhaba', language: 'Turkish' },
  { hello: 'Shalom', language: 'Hebrew' },
  { hello: 'Salut', language: 'Romanian' },
  { hello: 'Privet', language: 'Ukrainian' },
  { hello: 'Aloha', language: 'Hawaiian' },
  { hello: 'Jambo', language: 'Swahili' },
  { hello: 'Halo', language: 'Indonesian' },
  { hello: 'Hej', language: 'Swedish' },
  { hello: 'Marhaba', language: 'Persian' },
  { hello: 'Hallo', language: 'Dutch' },
  { hello: 'Góðan daginn', language: 'Icelandic' },
  { hello: 'Sziasztok', language: 'Hungarian' },
  { hello: 'Dia duit', language: 'Irish' },
  { hello: 'Szia', language: 'Slovak' },
  { hello: 'Kamusta', language: 'Filipino' },
  { hello: 'Salve', language: 'Latin' },
  { hello: 'Dzień dobry', language: 'Polish' },
  { hello: 'Sain baina uu', language: 'Mongolian' },
  { hello: 'Giá sou', language: 'Greek' },
  { hello: 'Ahoj', language: 'Czech' },
  { hello: 'Shwmae', language: 'Welsh' },
  { hello: 'Moïen', language: 'Luxembourgish' },
  { hello: 'Sveiki', language: 'Latvian' },
  { hello: 'Sveika', language: 'Lithuanian' },
  { hello: 'Hei', language: 'Norwegian' },
  { hello: 'Tere', language: 'Estonian' },
  { hello: 'Zdravo', language: 'Bosnian' },
  { hello: 'Salam', language: 'Azerbaijani' },
  { hello: 'Sannu', language: 'Hausa' },
  { hello: 'Hei hei', language: 'Finnish' },
  { hello: 'Talofa', language: 'Samoan' },
  { hello: 'Kumusta', language: 'Cebuano' },
  { hello: 'Kaixo', language: 'Basque' },
  { hello: 'Sanibonani', language: 'Zulu' },
  { hello: 'Sveikas', language: 'Lithuanian' },
  { hello: 'Dobrý deň', language: 'Slovak' },
  // Add more greetings here...
];